FROM golang:1.19-alpine3.17

RUN mkdir /app

ADD . /app

WORKDIR /app

RUN go build -o consumer

ENV USER=admin
ENV PASSWORD=admin
ENV HOST=localhost
ENV PORT=5672

CMD ["sh", "-c", "/app/consumer", "-user", "$USER", "-password", "$PASSWORD", "-host", "$HOST", "-port", "$PORT"]
